name: Build HTML
on:
  pull_request:
   branches:
   - main
   types: [closed]

  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: TheRealZoidberg/reusableTest/.github/workflows/ci_builder.yml@main
